server:
  port: 3000
view:
  path: '/Users/eugene/workspace/experiments/skeleton-node/server/views'
  engine: 'jade'
session:
  secret: '293828736g27f63g'
  key_name: 'sessionId'
  resave: false
  save_uninitialized: true
  secure_cookie: true
